### PR TITLE
[TASK] Update codius upload text

### PR DESCRIPTION
**Pull request by wilsonianb**
[Finishes #89727014]

### CODE REVIEW

**Comment by wilsonianb** [comment]
+r

**Comment by stevenzeiler** [comment]
:+1:

**Comment by stevenzeiler** [comment]
LGTM

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 2 +1s from the following folks:

* stevenzeiler* stevenzeiler

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
