### PR TITLE
[FEATURE] Upload to multiple remote hosts

### PR DESCRIPTION
**Pull request by wilsonianb**
Host urls are listed with the '--hosts' command line flag.
CODIUS_HOST environment variable is deprecated
[Finishes #89122638]

### CODE REVIEW

**Comment by wilsonianb** [comment]
+r

**Comment by codius-montecarlo** [comment]
Review has been requested, but I see no reviewers assigned. Here's who wins:

+r assign stevenzeiler

Come on down and claim your prize!

**Comment by codius-montecarlo** [comment]
Review has been requested, but I see no reviewers assigned. Here's who wins:

+r assign stevenzeiler

Come on down and claim your prize!

**Comment by tdfischer** [comment]
LGTM :+1:

**Comment by codius-montecarlo** [comment]
The build is good and I'm seeing 1 +1s from the following folks:

* tdfischer

As such, I'll attempt to merge and close this pull request.

**Pull request merged**
